apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    io.kompose.service: rest
  name: rest
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rest
  template:
    metadata:
      annotations:
      labels:
        io.kompose.service: rest
    spec:
      containers:
        - env:
            - name: AWS_ACCESS_KEY_ID
              value: admin
            - name: AWS_REGION
              value: us-east-1
            - name: AWS_SECRET_ACCESS_KEY
              value: password
            - name: CATALOG_IO__IMPL
              value: org.apache.iceberg.aws.s3.S3FileIO
            - name: CATALOG_S3_ENDPOINT
              value: http://minio:9000
            - name: CATALOG_WAREHOUSE
              value: s3a://warehouse/wh/
            - name: REST_PORT
              value: "8181"
          image: tabulario/iceberg-rest:latest
          name: rest
          ports:
            - containerPort: 8181
      restartPolicy: Always
