apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    io.kompose.service: rest
  name: rest
spec:
  ports:
    - name: "8181"
      port: 8181
      targetPort: 8181
  selector:
    io.kompose.service: rest
