apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    io.kompose.service: spark-iceberg
  name: spark-iceberg
spec:
  type: NodePort
  ports:
    - name: "8888"
      port: 8888
      targetPort: 8888
      nodePort: 30088
    - name: "8080"
      port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    io.kompose.service: spark-iceberg
